services:
  content:
    build:
      context: ./services/content
      dockerfile: Dockerfile
    depends_on:
      database:
        condition: service_started
    environment:
      - CONTENT_SERVICE_HOST=content
      - CONTENT_SERVICE_PORT=80
      - DB_SERVICE_HOST=database
      - DB_SERVICE_PORT=80
      - PROXY_HOST=${PROXY_HOST}
    networks:
      - content_network
  database:
    build:
      context: ./services/database
      dockerfile: Dockerfile
    depends_on:
      postgres-db:
        condition: service_started
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DB_GRPC_HOST=database
      - DB_GRPC_PORT=80
    networks:
      - content_network
      - database_network
  database-seed:
    build:
      context: ./services/database-seed
      dockerfile: Dockerfile
    depends_on:
      postgres-db:
        condition: service_started
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - INIT_DATABASE=${INIT_DATABASE}
      - PGPASSWORD=${DATABASE_PASSWORD}
    networks:
      - database_network
  postgres-db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    networks:
      - database_network
  nginx:
    build: .
    networks:
      - content_network
    ports: 
      - "55590:80"
networks:
  content_network:
    driver: bridge
  database_network:
    driver: bridge
