services:
  nginx:
    build: .
    networks:
      - content
    ports: 
      - "55590:80"
  cassandra-db:
    image: cassandra:latest
    networks:
      - database
networks:
  content:
  database:
